import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Andrei
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    public WelcomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bookList = new javax.swing.JComboBox<>();
        imagePanel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfTitle = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rentANDreturn = new javax.swing.JButton();
        rentpriceText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        buypriceText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameBill = new javax.swing.JLabel();
        rentStatus = new javax.swing.JLabel();
        paymentText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lostBook_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        receiptBuyer = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        receiptBookTitle = new javax.swing.JLabel();
        receiptPType = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        receiptPrice = new javax.swing.JLabel();
        receivedText = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        changeText = new javax.swing.JLabel();
        print_button = new javax.swing.JButton();
        showMembers_btn = new javax.swing.JButton();
        mainBanner = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(800, 430, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BOOK STORE");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Catching Fire", "The Martian", "Area 51 Interns Alien Summer 1", "Theodore Boone The Activist", "Reminders of Him", "It Ends With Us", "the sun and her flowers", "milk and honey", "The Fault in our Stars", "The Willoughbys", "Rich Dad Poor Dad", "The Power of Habit", "Ikigai", "The Hobbit", "A Secret Between Gentlemen", "Lord of the Rings The Fellowship of The Ring", "The Subtle Art of Not Giving a Fck", "Diary of Wimpy Kid", "Atomic Habits" }));
        bookList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookListActionPerformed(evt);
            }
        });
        jPanel2.add(bookList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, -1));

        imagePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1test/Harry Potter and the Deathly Hallows.jpg"))); // NOI18N
        jPanel2.add(imagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 150));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTitleActionPerformed(evt);
            }
        });
        jPanel1.add(tfTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, 30));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setText("Name:");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rentANDreturn.setText("Rent");
        rentANDreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentANDreturnActionPerformed(evt);
            }
        });
        jPanel4.add(rentANDreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel4.add(rentpriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel2.setText("Buy Price:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });
        jPanel4.add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        jPanel4.add(buypriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel3.setText("Rent Price:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setText("Billing Name:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel4.add(nameBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 20));

        rentStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(rentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 40));

        paymentText.setToolTipText("Input your payment here");
        paymentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTextActionPerformed(evt);
            }
        });
        jPanel4.add(paymentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("$");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Payment");
        jLabel11.setToolTipText("");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lostBook_btn.setText("Book is Lost");
        lostBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostBook_btnActionPerformed(evt);
            }
        });
        jPanel4.add(lostBook_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Receipt");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setText("Billed to:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel5.add(receiptBuyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel8.setText("Purchase Type:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setText("Book Title:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel5.add(receiptBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));
        jPanel5.add(receiptPType, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel7.setText("Price:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel5.add(receiptPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));
        jPanel5.add(receivedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel13.setText("Received:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel14.setText("Change:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel5.add(changeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        print_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        print_button.setText("Print");
        print_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_buttonActionPerformed(evt);
            }
        });
        jPanel5.add(print_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        showMembers_btn.setText("Members");
        showMembers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMembers_btnActionPerformed(evt);
            }
        });

        mainBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1test/output.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addComponent(showMembers_btn))
                            .addComponent(mainBanner)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(showMembers_btn))
                    .addComponent(mainBanner))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String userName = "";
    //static Book[] bookArray = new Book[20];
    
    
    static Book[] bookArray = new Book[20];
    public static void setArray() {
    
    bookArray[0] = new Book("Atomic Habits", 3, 21.99);
    bookArray[1] = new Book("Diary of Wimpy Kid", 3, 9.99);
    bookArray[2] = new Book("The Subtle Art of Not Giving a Fck", 3, 7.77);
    bookArray[3] = new Book("Lord of the Rings The Fellowship of The Ring", 3, 8.99);
    bookArray[4] = new Book("A Secret Between Gentlemen", 4, 10.99);
    bookArray[5] = new Book("The Hobbit", 3.2, 10.99);
    bookArray[6] = new Book("Ikigai", 3, 10.99);
    bookArray[7] = new Book("The Power of Habit", 2.79, 10.99);
    bookArray[8] = new Book("Rich Dad Poor Dad", 2.99, 16.99);
    bookArray[9] = new Book("The Willoughbys", 5, 15.99);
    bookArray[10] = new Book("The Fault in our Stars", 3, 10.70);
    bookArray[11] = new Book("milk and honey", 5, 10.99);
    bookArray[12] = new Book("the sun and her flowers", 3, 14.50);
    bookArray[13] = new Book("It Ends With Us", 4, 10.99);
    bookArray[14] = new Book("Reminders of Him", 3, 10.99);
    bookArray[15] = new Book("Theodore Boone The Activist", 3, 24.99);
    bookArray[16] = new Book("Area 51 Interns Alien Summer 1", 3, 29.99);
    bookArray[17] = new Book("The Martian", 4, 29.39);
    bookArray[18] = new Book("Catching Fire", 5, 17.99);
    bookArray[19] = new Book("Harry Potter and the Deathly Hallows", 6, 34.99);
    
    }
        
   
  
    
    private void tfTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTitleActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        String title = tfTitle.getText();
        userName = title;
        setTitle("Hello, " + userName + "!");
        nameBill.setText(userName);
    }//GEN-LAST:event_btnOKActionPerformed


    private void bookListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookListActionPerformed
        // TODO add your handling code here:  
        
 
        for(int i = 0;i < 20;i++){
           
            if(bookArray[i].getBookTitle().equals(bookList.getSelectedItem())) {
                imagePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1test/" + bookArray[i].getBookTitle() + ".jpg")));
                rentpriceText.setText("$" + Double.toString(bookArray[i].getRentPrice()));
                
                if (bookArray[i].isBought()){
                    rentStatus.setText(bookArray[i].isSettled() ? "Settled for Missing book" : "Owned");
                    
                } else if (!bookArray[i].isBought() && !bookArray[i].isMissing()) {
                    rentStatus.setText(bookArray[i].isRented() ? "Rented" : "Not Rented or Owned");
                } else if (bookArray[i].isMissing()) {
                    rentStatus.setText("Missing");
                }
                
               // buypriceText.setText("$" + Double.toString(bookArray[i].getBuyPrice()));
                if(!bookArray[i].isBought() && !bookArray[i].isRented() && !bookArray[i].isMissing()) {
                    rentANDreturn.setEnabled(true);
                    rentANDreturn.setText("Rent");
                    lostBook_btn.setEnabled(false);
                } else if (bookArray[i].isRented()) {
                    rentANDreturn.setText("Return");
                } else if (bookArray[i].isMissing()) {
                    rentANDreturn.setEnabled(false);
                }
            }
        }
        
        for(int i = 0;i < 20;i++){
        
            if(bookArray[i].getBookTitle().equals(bookList.getSelectedItem())) {
                imagePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1test/" + bookArray[i].getBookTitle() + ".jpg")));
                buypriceText.setText("$" + Double.toString(bookArray[i].getBuyPrice()));

                lostBook_btn.setEnabled(bookArray[i].isRented());
            }
        }
        
        
         // NOI18N


        
        
        
    }//GEN-LAST:event_bookListActionPerformed

    private void rentANDreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentANDreturnActionPerformed
        // TODO add your handling code here:
        Book subjectBook = findBook();

        String userPayment = paymentText.getText();
        boolean isMoneyEnough = Double.parseDouble(userPayment) > subjectBook.getRentPrice();
        


        if(subjectBook.getBookTitle().equals(bookList.getSelectedItem())) {
            //bookArray[i].setisRented(true);
            if(rentANDreturn.getText().equals("Rent") && isMoneyEnough) {
                receiptBuyer.setText(nameBill.getText());
                receiptPType.setText("Renting");
                receiptPrice.setText(rentpriceText.getText());
                receiptBookTitle.setText("" + bookList.getSelectedItem());
                subjectBook.setisRented(true);
                rentStatus.setText("Rented");

                changeText.setText("$" + (Double.parseDouble(paymentText.getText()) - subjectBook.getRentPrice()));
                receivedText.setText("$" + paymentText.getText());
                lostBook_btn.setEnabled(true);

                rentANDreturn.setText("Return");
            }

            else if (rentANDreturn.getText().equals("Return")) {
                receiptBuyer.setText(nameBill.getText());
                receiptPType.setText("Returned");
                receiptPrice.setText(rentpriceText.getText());
                receiptBookTitle.setText("" + bookList.getSelectedItem());

                rentStatus.setText("Not Rented or Owned");
                changeText.setText("N/A");
                receivedText.setText("N/A");

                subjectBook.setisRented(false);
                lostBook_btn.setEnabled(false);
                rentANDreturn.setText("Rent");
            } else if (!isMoneyEnough) {
              JOptionPane.showMessageDialog(this, "Insufficient funds.", "No money", 2);
            } else {
            JOptionPane.showMessageDialog(this, "Please pay the required amount.", "Error", 2);
            }
            
        }
        
        
        
    }//GEN-LAST:event_rentANDreturnActionPerformed

    private Book findBook() {
        
        for(int i = 0;i < 20;i++){

            if(bookArray[i].getBookTitle().equals(bookList.getSelectedItem())) {
                return bookArray[i];
            }
        }
        return null;
    }
    
    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        // TODO add your handling code here:
        Book subjectBook = findBook();

        String userPayment = paymentText.getText();
        
        boolean isMoneyEnough = Double.parseDouble(userPayment) > subjectBook.getBuyPrice();
        
        if (isMoneyEnough) {
           subjectBook.setisBought(true);
            rentANDreturn.setEnabled(false);
           double change = Double.parseDouble(userPayment) - subjectBook.getBuyPrice();
           changeText.setText("$" + change);
           
           
           if (!subjectBook.isMissing()) {
               rentStatus.setText("Owned");
               receiptPType.setText("Ownership");
               lostBook_btn.setEnabled(false);
           } else {
               rentStatus.setText("Settled for Missing book");
               receiptPType.setText("Settlement");
               subjectBook.setisSettled(true);
               subjectBook.setisMissing(false);
               lostBook_btn.setEnabled(false);
               rentANDreturn.setEnabled(true);
               rentANDreturn.setText("Rent");
           }

           receiptBuyer.setText(nameBill.getText());
           receiptPrice.setText(buypriceText.getText());
           receiptBookTitle.setText("" + bookList.getSelectedItem());

           receivedText.setText("$" + paymentText.getText());
        } else if (!isMoneyEnough) {
            JOptionPane.showMessageDialog(this, "Insufficient funds.", "No money", 2);
        } else {
            JOptionPane.showMessageDialog(this, "Please pay the required amount.", "Error", 2);
        }
       
        

        
        
    }//GEN-LAST:event_buyButtonActionPerformed

    private void paymentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTextActionPerformed

    private void print_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_buttonActionPerformed
        // TODO add your handling code here:
        
        String print_this = 
                "===RECEIPT===" +
                "\nBook Title: " +     receiptBookTitle.getText() +
                "\nPurchase Type: " +  receiptPType.getText() +
                "\nPrice: " +          receiptPrice.getText() +
                "\nReceived: " +       receivedText.getText() +
                "\nChange: " +         changeText.getText() +
                "\nBilled to: " +      receiptBuyer.getText() +
                "\n=============";
                        
       JOptionPane.showMessageDialog(this, print_this, "Receipt", JOptionPane.INFORMATION_MESSAGE, null);
       
    }//GEN-LAST:event_print_buttonActionPerformed

    private void lostBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostBook_btnActionPerformed
        // TODO add your handling code here:
        Book subjectBook = findBook();
        ImageIcon icon = new ImageIcon("/javaapplication1test/" + subjectBook.getBookTitle() + ".png");
        JOptionPane.showMessageDialog(this, "If you lost or can't return the book, you have to pay for the book.", "Lost Book", 1, icon);
     
 
        subjectBook.setisRented(false);
        subjectBook.setisMissing(true);
        rentANDreturn.setEnabled(false);
        rentStatus.setText("Missing");
    }//GEN-LAST:event_lostBook_btnActionPerformed

    private void showMembers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMembers_btnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Chris Andrei\nEumir Maling\nChristine Sorronda\nJohn Vincent Gamali\nQylle Christian Quiño", "Book Rental System", 1, null);
    }//GEN-LAST:event_showMembers_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        setArray();
        
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookList;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton buyButton;
    private javax.swing.JLabel buypriceText;
    private javax.swing.JLabel changeText;
    private javax.swing.JLabel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lostBook_btn;
    private static javax.swing.JLabel mainBanner;
    private javax.swing.JLabel nameBill;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField paymentText;
    private javax.swing.JButton print_button;
    private javax.swing.JLabel receiptBookTitle;
    private javax.swing.JLabel receiptBuyer;
    private javax.swing.JLabel receiptPType;
    private javax.swing.JLabel receiptPrice;
    private javax.swing.JLabel receivedText;
    private javax.swing.JButton rentANDreturn;
    private javax.swing.JLabel rentStatus;
    private javax.swing.JLabel rentpriceText;
    private javax.swing.JButton showMembers_btn;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables
}
